### ISSUE TITLE
Launcher Hijack major problems on Kindle Fire 8 2017

### ISSUE THREAD

**Issue by RichardMW23** [BaronKiko/LauncherHijackV2#7]
First, I think that Launcher Hijack is potentially a great tool and mostly works.

I installed Launcher Hijack on my  Kindle Fire 8 2017 and ran into 2 major problems.

Running Hijack & Nova Launcher, I set "persistent search bar" in Nova options.
The search bar shows up but does not work.
I can't type anything in the search bar and get it to do a google search.
If I click in the search bar, I see a list of recent searches. I can't select any of them.

If I run Nova Launcher as an app in standard Fire launcher, it opens up and I can search.

Second problem.
Running Hijack & Nova Launcher, I can't add a widget to any screen.
I can search the list of widgets, but if I select one then the Fire settings screen opens and the widget is not put on any screen.

Yes, I read all your posted trouble shooting tips and tried them with no sucess.

**Comment by BaronKiko** [comment]
Widgets only work an google now due to fire restrictions (basically no root). I haven't tried this but a user posted this the other day as a work around: [https://forum.xda-developers.com/amazon-fire/general/root-required-widgets-preferred-launcher-t3637814](url)
And I'm pretty sure the persistent nav bar is a widget behind the scenes so will probably fix that too. If it doesn't fix it then it's still a launcher issue and completely out of my hands.
